/**************Created for functionality purpose**********************/
package view;

import controller.AddGroup_Controller;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.*;

public class AddGroup_UI extends javax.swing.JFrame {

    DefaultListModel data;
    /**
     * Creates new form AddGroup_UI
     */
    public AddGroup_UI() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupName_tf = new javax.swing.JTextField();
        selectGroups_list = new javax.swing.JScrollPane();
        nullGroups = new javax.swing.JList<>();
        addGroup_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nullGroups.setModel(createNullGroupsModel());
        nullGroups.setToolTipText("");
        selectGroups_list.setViewportView(nullGroups);

        addGroup_btn.setText("Add Group");
        addGroup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroup_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectGroups_list, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addGroup_btn)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(groupName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 250, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(groupName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(selectGroups_list, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(addGroup_btn)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGroup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroup_btnActionPerformed
        AddGroup_Controller controller = new AddGroup_Controller();
        try{
            controller.addGroup(this);
            controller.addGroupShowSucceed(this);
        }
        catch(Exception ex){
            controller.addGroupShowError(ex,this);
        }
    }//GEN-LAST:event_addGroup_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGroup_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGroup_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGroup_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGroup_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGroup_UI().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup_btn;
    private javax.swing.JTextField groupName_tf;
    private javax.swing.JList<String> nullGroups;
    private javax.swing.JScrollPane selectGroups_list;
    // End of variables declaration//GEN-END:variables

    public String getGroupName(){
        return groupName_tf.getText();
    }
    
    public List<String> getSelectedNullGroups(){
        return nullGroups.getSelectedValuesList();
    }
    
    public JList<String> getnullGroupsJList(){
        return nullGroups;
    }
    
    //Shows the current existing groups in a list, gets it from the controller
    private DefaultListModel createNullGroupsModel(){
        data = new DefaultListModel();
        AddGroup_Controller cont = new AddGroup_Controller();
        
        for(int i=0;i < cont.getNullGroupsList().size(); i++){
            data.addElement(cont.getNullGroupsList().get(i));
        }
        return data;
    }
}
