package Model;
// Generated 11/11/2019 02:12:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Houses generated by hbm2java
 */
public class Houses  implements java.io.Serializable {


     private Integer idhouse;
     private String name;
     private Set groupses = new HashSet(0);

    public Houses() {
    }

	
    public Houses(String name) {
        this.name = name;
    }
    public Houses(String name, Set groupses) {
       this.name = name;
       this.groupses = groupses;
    }
   
    public Integer getIdhouse() {
        return this.idhouse;
    }
    
    public void setIdhouse(Integer idhouse) {
        this.idhouse = idhouse;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getGroupses() {
        return this.groupses;
    }
    
    public void setGroupses(Set groupses) {
        this.groupses = groupses;
    }




}


